# https://taskfile.dev

version: '3'

tasks:
  db:up:
    cmds:
      - docker compose up
  db:down:
    cmds:
      - docker compose down

  db:migrate:create:
    cmds:
      - migrate create -ext sql -dir internal/database/migrations -seq {{.name}}
  db:migrate:up:
    cmds:
      - migrate -path internal/database/migrations -database postgres://postgres:postgres@localhost:5433/slackclonedb?sslmode=disable up 1
  db:migrate:down:
    cmds:
      - migrate -path internal/database/migrations -database postgres://postgres:postgres@localhost:5433/slackclonedb?sslmode=disable down 1
  db:migrate:force:
    cmds:
      - migrate -path internal/database/migrations -database postgres://postgres:postgres@localhost:5433/slackclonedb?sslmode=disable force {{.version}}
  db:migrate:version:
    cmds:
      - migrate -path internal/database/migrations -database postgres://postgres:postgres@localhost:5433/slackclonedb?sslmode=disable version
  db:migrate:goto:
    cmds:
      - migrate -path internal/database/migrations -database postgres://postgres:postgres@localhost:5433/slackclonedb?sslmode=disable goto {{.version}}

  sqlc:generate:
    cmds:
      - sqlc generate

  dev:b:
    cmds:
      - air
    silent: false
  dev:f:
    cmds:
      - pnpm css:dev & pnpm js:dev

  f:check:
    cmds:
      - pnpm check
  f:format:
    cmds:
      - pnpm format
  f:build:
    cmds:
      - pnpm build
  f:preview:
    cmds:
      - pnpm preview
